name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build and Test
        run: |
          npm run build
          npm test

      - name: Deploy to GitHub Pages
        if: success()
        run: |
          git config --global user.name $user_name
          git config --global user.email $user_email
          npm run build
          npx gh-pages -d dist -b gh-pages

  update-readme:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README with deployment URL
        run: |
          DEPLOY_URL=$(npx gh-pages -d dist -b gh-pages --get-url)
          sed -i 's#Deployment URL:.*#Deployment URL: '"$DEPLOY_URL"'#' README.md
